#!/bin/bash

# echo "Cambiando los permisos del archivo /etc/resolv.conf para editarlo ..."
sudo chmod 777 /etc/resolv.conf

# echo "Agregando la direccion IP de DNS al archivo /etc/resolv.conf ..."
echo "# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)" > /etc/resolv.conf
echo "#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN" >> /etc/resolv.conf
echo "domain salta.dc.fi.uba.ar" >> /etc/resolv.conf 
echo "search salta.dc.fi.uba.ar" >> /etc/resolv.conf
echo "nameserver 10.11.3.68" >> /etc/resolv.conf

# echo "Restableciendo los permisos del archivo /etc/resolv.conf ..."
sudo chmod 644 /etc/resolv.conf

exit 0


